### ISSUE TITLE
schema 정의

### ISSUE THREAD

**Issue by koh1260** [git-in-official/server#17]
## 👾 작업 사항
- 스키마를 정의하한다.

## 🦄 To-do
- [ ] 상호작용 테이블 생성
- [ ] 칭호 테이블 생성
- [ ] 칭호 획득 테이블 생성
- [ ] 회원 테이블에 대표 칭호 컬럼 생성
